"""add_interview_module

Revision ID: 0d92dce5a1cc
Revises: eac9635eee87
Create Date: 2026-08-23 01:04:49.430747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d92dce5a1cc'
down_revision: Union[str, Sequence[str], None] = 'eac9635eee87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('interview_type', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_interview_sessions_created_at'), 'career_interview_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_career_interview_sessions_id'), 'career_interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_career_interview_sessions_student_id'), 'career_interview_sessions', ['student_id'], unique=False)
    op.create_table('career_interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('expected_topics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['career_interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_interview_questions_id'), 'career_interview_questions', ['id'], unique=False)
    op.create_index(op.f('ix_career_interview_questions_session_id'), 'career_interview_questions', ['session_id'], unique=False)
    op.create_table('career_interview_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['career_interview_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index(op.f('ix_career_interview_responses_id'), 'career_interview_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_interview_responses_id'), table_name='career_interview_responses')
    op.drop_table('career_interview_responses')
    op.drop_index(op.f('ix_career_interview_questions_session_id'), table_name='career_interview_questions')
    op.drop_index(op.f('ix_career_interview_questions_id'), table_name='career_interview_questions')
    op.drop_table('career_interview_questions')
    op.drop_index(op.f('ix_career_interview_sessions_student_id'), table_name='career_interview_sessions')
    op.drop_index(op.f('ix_career_interview_sessions_id'), table_name='career_interview_sessions')
    op.drop_index(op.f('ix_career_interview_sessions_created_at'), table_name='career_interview_sessions')
    op.drop_table('career_interview_sessions')
    # ### end Alembic commands ###
