"""add_career_roadmap

Revision ID: 4777f18928ad
Revises: f16e43d5a09d
Create Date: 2026-08-23 09:34:08.466798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4777f18928ad'
down_revision: Union[str, Sequence[str], None] = 'f16e43d5a09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_goals_id'), 'career_goals', ['id'], unique=False)
    op.create_index(op.f('ix_career_goals_student_id'), 'career_goals', ['student_id'], unique=False)
    op.create_table('roadmap_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_tasks_id'), 'roadmap_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_tasks_student_id'), 'roadmap_tasks', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_tasks_student_id'), table_name='roadmap_tasks')
    op.drop_index(op.f('ix_roadmap_tasks_id'), table_name='roadmap_tasks')
    op.drop_table('roadmap_tasks')
    op.drop_index(op.f('ix_career_goals_student_id'), table_name='career_goals')
    op.drop_index(op.f('ix_career_goals_id'), table_name='career_goals')
    op.drop_table('career_goals')
    # ### end Alembic commands ###
