"""coding_platform

Revision ID: 6338130d6568
Revises: 9841f37985e0
Create Date: 2026-08-23 00:04:50.386037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6338130d6568'
down_revision: Union[str, Sequence[str], None] = '9841f37985e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_coding_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('hints', sa.JSON(), nullable=True),
    sa.Column('starter_code', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_coding_problems_id'), 'career_coding_problems', ['id'], unique=False)
    op.create_index(op.f('ix_career_coding_problems_slug'), 'career_coding_problems', ['slug'], unique=True)
    op.create_table('career_coding_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('best_runtime_ms', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('first_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['career_coding_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_coding_progress_id'), 'career_coding_progress', ['id'], unique=False)
    op.create_index(op.f('ix_career_coding_progress_student_id'), 'career_coding_progress', ['student_id'], unique=False)
    op.create_table('career_coding_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('memory_kb', sa.Integer(), nullable=True),
    sa.Column('test_cases_passed', sa.Integer(), nullable=True),
    sa.Column('total_test_cases', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['career_coding_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_coding_submissions_id'), 'career_coding_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_career_coding_submissions_student_id'), 'career_coding_submissions', ['student_id'], unique=False)
    op.create_table('career_coding_testcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['career_coding_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_coding_testcases_id'), 'career_coding_testcases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_coding_testcases_id'), table_name='career_coding_testcases')
    op.drop_table('career_coding_testcases')
    op.drop_index(op.f('ix_career_coding_submissions_student_id'), table_name='career_coding_submissions')
    op.drop_index(op.f('ix_career_coding_submissions_id'), table_name='career_coding_submissions')
    op.drop_table('career_coding_submissions')
    op.drop_index(op.f('ix_career_coding_progress_student_id'), table_name='career_coding_progress')
    op.drop_index(op.f('ix_career_coding_progress_id'), table_name='career_coding_progress')
    op.drop_table('career_coding_progress')
    op.drop_index(op.f('ix_career_coding_problems_slug'), table_name='career_coding_problems')
    op.drop_index(op.f('ix_career_coding_problems_id'), table_name='career_coding_problems')
    op.drop_table('career_coding_problems')
    # ### end Alembic commands ###
