"""career_core

Revision ID: 7b5072ac38fe
Revises: d9b2f292f4ac
Create Date: 2026-08-22 23:13:38.167559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5072ac38fe'
down_revision: Union[str, Sequence[str], None] = 'd9b2f292f4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('source_context_hash', sa.String(), nullable=True),
    sa.Column('model_provider', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_id'), 'ai_insights', ['id'], unique=False)
    op.create_index(op.f('ix_ai_insights_student_id'), 'ai_insights', ['student_id'], unique=False)
    op.create_table('career_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('target_domain', sa.String(), nullable=True),
    sa.Column('career_objective', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('internships', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_profiles_id'), 'career_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_career_profiles_student_id'), 'career_profiles', ['student_id'], unique=True)
    op.create_table('career_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_items', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_progress_id'), 'career_progress', ['id'], unique=False)
    op.create_index(op.f('ix_career_progress_student_id'), 'career_progress', ['student_id'], unique=False)
    op.create_table('career_readiness_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('coding_score', sa.Float(), nullable=True),
    sa.Column('aptitude_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('communication_score', sa.Float(), nullable=True),
    sa.Column('interview_score', sa.Float(), nullable=True),
    sa.Column('resume_score', sa.Float(), nullable=True),
    sa.Column('projects_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_readiness_scores_id'), 'career_readiness_scores', ['id'], unique=False)
    op.create_index(op.f('ix_career_readiness_scores_student_id'), 'career_readiness_scores', ['student_id'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_evaluated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_skills_id'), 'student_skills', ['id'], unique=False)
    op.create_index(op.f('ix_student_skills_student_id'), 'student_skills', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_skills_student_id'), table_name='student_skills')
    op.drop_index(op.f('ix_student_skills_id'), table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_career_readiness_scores_student_id'), table_name='career_readiness_scores')
    op.drop_index(op.f('ix_career_readiness_scores_id'), table_name='career_readiness_scores')
    op.drop_table('career_readiness_scores')
    op.drop_index(op.f('ix_career_progress_student_id'), table_name='career_progress')
    op.drop_index(op.f('ix_career_progress_id'), table_name='career_progress')
    op.drop_table('career_progress')
    op.drop_index(op.f('ix_career_profiles_student_id'), table_name='career_profiles')
    op.drop_index(op.f('ix_career_profiles_id'), table_name='career_profiles')
    op.drop_table('career_profiles')
    op.drop_index(op.f('ix_ai_insights_student_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
