"""assessments

Revision ID: 9841f37985e0
Revises: 7b5072ac38fe
Create Date: 2026-08-22 23:41:49.559435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9841f37985e0'
down_revision: Union[str, Sequence[str], None] = '7b5072ac38fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_assessments_category'), 'career_assessments', ['category'], unique=False)
    op.create_index(op.f('ix_career_assessments_id'), 'career_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_career_assessments_title'), 'career_assessments', ['title'], unique=False)
    op.create_index(op.f('ix_career_assessments_topic'), 'career_assessments', ['topic'], unique=False)
    op.create_table('career_assessment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_saved_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('incorrect_answers', sa.Integer(), nullable=True),
    sa.Column('unanswered', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('ai_insight', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['career_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_assessment_attempts_id'), 'career_assessment_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_career_assessment_attempts_student_id'), 'career_assessment_attempts', ['student_id'], unique=False)
    op.create_table('career_assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('negative_marks', sa.Float(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_option_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['career_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_assessment_questions_id'), 'career_assessment_questions', ['id'], unique=False)
    op.create_index(op.f('ix_career_assessment_questions_topic'), 'career_assessment_questions', ['topic'], unique=False)
    op.create_table('career_assessment_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('selected_option_id', sa.String(), nullable=True),
    sa.Column('is_answered', sa.Boolean(), nullable=True),
    sa.Column('marked_for_review', sa.Boolean(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['career_assessment_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['career_assessment_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_assessment_answers_id'), 'career_assessment_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_assessment_answers_id'), table_name='career_assessment_answers')
    op.drop_table('career_assessment_answers')
    op.drop_index(op.f('ix_career_assessment_questions_topic'), table_name='career_assessment_questions')
    op.drop_index(op.f('ix_career_assessment_questions_id'), table_name='career_assessment_questions')
    op.drop_table('career_assessment_questions')
    op.drop_index(op.f('ix_career_assessment_attempts_student_id'), table_name='career_assessment_attempts')
    op.drop_index(op.f('ix_career_assessment_attempts_id'), table_name='career_assessment_attempts')
    op.drop_table('career_assessment_attempts')
    op.drop_index(op.f('ix_career_assessments_topic'), table_name='career_assessments')
    op.drop_index(op.f('ix_career_assessments_title'), table_name='career_assessments')
    op.drop_index(op.f('ix_career_assessments_id'), table_name='career_assessments')
    op.drop_index(op.f('ix_career_assessments_category'), table_name='career_assessments')
    op.drop_table('career_assessments')
    # ### end Alembic commands ###
