"""resume_builder

Revision ID: eac9635eee87
Revises: 6338130d6568
Create Date: 2026-08-23 00:20:08.849479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac9635eee87'
down_revision: Union[str, Sequence[str], None] = '6338130d6568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('github', sa.String(length=255), nullable=True),
    sa.Column('portfolio', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_resumes_id'), 'career_resumes', ['id'], unique=False)
    op.create_index(op.f('ix_career_resumes_student_id'), 'career_resumes', ['student_id'], unique=False)
    op.create_table('career_resume_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['career_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_resume_achievements_id'), 'career_resume_achievements', ['id'], unique=False)
    op.create_table('career_resume_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['career_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_resume_activities_id'), 'career_resume_activities', ['id'], unique=False)
    op.create_table('career_resume_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('content_quality', sa.Float(), nullable=True),
    sa.Column('skills_strength', sa.Float(), nullable=True),
    sa.Column('experience_quality', sa.Float(), nullable=True),
    sa.Column('project_quality', sa.Float(), nullable=True),
    sa.Column('education_completeness', sa.Float(), nullable=True),
    sa.Column('formatting_score', sa.Float(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('missing_information', sa.JSON(), nullable=True),
    sa.Column('actionable_improvements', sa.JSON(), nullable=True),
    sa.Column('target_job_title', sa.String(length=255), nullable=True),
    sa.Column('job_match_score', sa.Float(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('missing_keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['career_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_resume_analyses_id'), 'career_resume_analyses', ['id'], unique=False)
    op.create_table('career_resume_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.String(length=50), nullable=True),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('credential_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['career_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_resume_certifications_id'), 'career_resume_certifications', ['id'], unique=False)
    op.create_table('career_resume_educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('gpa', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['career_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_resume_educations_id'), 'career_resume_educations', ['id'], unique=False)
    op.create_table('career_resume_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['career_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_resume_experiences_id'), 'career_resume_experiences', ['id'], unique=False)
    op.create_table('career_resume_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('live_url', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['career_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_resume_projects_id'), 'career_resume_projects', ['id'], unique=False)
    op.create_table('career_resume_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('proficiency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['career_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_resume_skills_id'), 'career_resume_skills', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_resume_skills_id'), table_name='career_resume_skills')
    op.drop_table('career_resume_skills')
    op.drop_index(op.f('ix_career_resume_projects_id'), table_name='career_resume_projects')
    op.drop_table('career_resume_projects')
    op.drop_index(op.f('ix_career_resume_experiences_id'), table_name='career_resume_experiences')
    op.drop_table('career_resume_experiences')
    op.drop_index(op.f('ix_career_resume_educations_id'), table_name='career_resume_educations')
    op.drop_table('career_resume_educations')
    op.drop_index(op.f('ix_career_resume_certifications_id'), table_name='career_resume_certifications')
    op.drop_table('career_resume_certifications')
    op.drop_index(op.f('ix_career_resume_analyses_id'), table_name='career_resume_analyses')
    op.drop_table('career_resume_analyses')
    op.drop_index(op.f('ix_career_resume_activities_id'), table_name='career_resume_activities')
    op.drop_table('career_resume_activities')
    op.drop_index(op.f('ix_career_resume_achievements_id'), table_name='career_resume_achievements')
    op.drop_table('career_resume_achievements')
    op.drop_index(op.f('ix_career_resumes_student_id'), table_name='career_resumes')
    op.drop_index(op.f('ix_career_resumes_id'), table_name='career_resumes')
    op.drop_table('career_resumes')
    # ### end Alembic commands ###
