import React from 'react';
import { RoleGuard } from '@campus-os/ui';
import { Target, AlertCircle, Clock, Map, BookOpen } from 'lucide-react';

export const CareerRoadmap = () => {
  // Parse user roles from Team 1's auth state to maintain identical auth pattern
  const userStr = localStorage.getItem('user');
  const user = userStr ? JSON.parse(userStr) : null;
  const userRoles = user?.roles || [];

  return (
    <RoleGuard allowedRoles={['STUDENT']} userRoles={userRoles}>
      <div className="p-6 max-w-6xl mx-auto space-y-8">
        <div>
          <h2 className="text-3xl font-bold mb-2">Career Roadmap & Skill Gap Analysis</h2>
          <p className="text-gray-500">
            A personalized path generated by AI based on your career goals, assessments, and current skills.
          </p>
        </div>

        <div className="bg-white border rounded-xl p-8 shadow-sm text-center">
          <Clock className="w-16 h-16 text-indigo-300 mx-auto mb-6 animate-pulse" />
          <h3 className="text-2xl font-bold mb-2">AI Roadmap Generation Pending</h3>
          <p className="text-gray-500 max-w-lg mx-auto mb-8">
            Your career roadmap is waiting for the AI integration to be completed. 
            Once the Team 3 AI roadmap service is available, you will see a detailed path including 
            your exact missing skills, a learning sequence, suggested resources, and project suggestions.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-left">
            <div className="p-4 bg-gray-50 border border-dashed rounded-lg">
              <Target className="w-8 h-8 text-gray-400 mb-3" />
              <h4 className="font-semibold text-gray-700">Skill Gap Analysis</h4>
              <p className="text-sm text-gray-500 mt-1">Pending AI response comparing your skills to industry requirements.</p>
            </div>
            
            <div className="p-4 bg-gray-50 border border-dashed rounded-lg">
              <BookOpen className="w-8 h-8 text-gray-400 mb-3" />
              <h4 className="font-semibold text-gray-700">Learning Resources</h4>
              <p className="text-sm text-gray-500 mt-1">Pending recommended courses and tutorials to bridge your gap.</p>
            </div>

            <div className="p-4 bg-gray-50 border border-dashed rounded-lg">
              <Map className="w-8 h-8 text-gray-400 mb-3" />
              <h4 className="font-semibold text-gray-700">Project Suggestions</h4>
              <p className="text-sm text-gray-500 mt-1">Pending AI-generated project ideas to build your portfolio.</p>
            </div>
          </div>

          <div className="mt-8 flex items-start space-x-2 text-sm text-blue-700 bg-blue-50 p-4 rounded-lg border border-blue-200 inline-flex text-left">
            <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold mb-1">Integration Status: Waiting on Team 3</p>
              <p className="text-blue-600 text-xs">
                Requires the <code>POST /ai/career/roadmap</code> API from the Team 3 AI service to generate real insights.
              </p>
            </div>
          </div>
        </div>
      </div>
    </RoleGuard>
  );
};
